# Introduction to Numpy 

## Importing Numpy

The Numerical Python package _numpy_ is usually imported using _np_ as an alias. 

In [1]:
import numpy as np
np.__version__

'1.16.5'

## Creating _numpy_ Arrays from a Python list

We can use np.array to create arrays from Python lists:

In [2]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

 The data type will be determined by the minimum type required to hold the objects in the sequence. If we want to explicitly set the data type of the resulting array, we can use the dtype
keyword:

In [3]:
np.array([1,2,3,4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lists, NumPy arrays can explicitly be multidimensional; here’s
one way of initializing a multidimensional array using a list of lists:

In [4]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating _numpy_ Arrays from scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines
built into NumPy. Here are several examples:

In [5]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.14723991, 0.83451518, 0.56343597],
       [0.1169698 , 0.76995437, 0.2746147 ],
       [0.915836  , 0.30740824, 0.39784941]])

In [10]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.20043181, -0.02625885, -1.18605397],
       [-0.40281857,  1.25132093, -1.01922671],
       [-1.10637891,  0.35749662, -1.78696954]])

In [11]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 4, 6],
       [5, 2, 9],
       [8, 6, 5]])

In [13]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([0., 0., 0.])

## Numpy standard Data Types

| Data type | Description |
| ---: | :--- |
| bool_ | Boolean (True or False) stored as a byte |
| int_ | Default integer type (same as C long; normally either int64 or int32) |
| intc | Identical to C int (normally int32 or int64) |
| intp | Integer used for indexing (same as C ssize_t; normally either int32 or int64) |
| int8 | Byte (–128 to 127) |
| int16 | Integer (–32768 to 32767) |
| int32 | Integer (–2147483648 to 2147483647) |
| int64 | Integer (–9223372036854775808 to 9223372036854775807) |
| uint8 | Unsigned integer (0 to 255) |
| uint16 | Unsigned integer (0 to 65535) |
| uint32 | Unsigned integer (0 to 4294967295) |
| uint64 | Unsigned integer (0 to 18446744073709551615) |
| float_ | Shorthand for float64 |
| float16 | Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa |
| float32 | Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa |
| float64 | Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa |
| complex_ | Shorthand for complex128 |
| complex64 | Complex number, represented by two 32-bit floats |
| complex128 | Complex number, represented by two 64-bit floats |

## Numpy Array Attributes

Here are listed  some useful array attributes.

In [13]:
x = np.random.randint(10, size=(3, 4, 5))
print("Number of dimensions -> ndim: ", x.ndim)
print("Size of each dimension -> shape: ", x.shape)
print("Total size of the array -> size: ", x.size)
print("Data type of the array -> dtype: ", x.dtype)
print("Size in bytes of each array element -> itemsize: ", x.itemsize)
print("Total size of the array -> nbytes: ", x.nbytes)

Number of dimensions -> ndim:  3
Size of each dimension -> shape:  (3, 4, 5)
Total size of the array -> size:  60
Data type of the array -> dtype:  int32
Size in bytes of each array element -> itemsize:  4
Total size of the array -> nbytes:  240
