# Indexing and slicing of arrays

## Indexing of arrays

Indexing arrays works just as with Python lists, using square brackets and starting with the offset in zero. For multidimensional arrays, you access items using a comma-separated tuple of indices. You can change the array by asigning new values with the index notation.

In [1]:
import numpy as np

x = np.random.randint(10, size=(3,4))
x

array([[3, 5, 7, 2],
       [8, 9, 0, 3],
       [8, 6, 2, 2]])

In [2]:
x[2,1]

6

In [3]:
x[2,1] = 25
x

array([[ 3,  5,  7,  2],
       [ 8,  9,  0,  3],
       [ 8, 25,  2,  2]])

## Array slicing and accessing subarrays

The NumPy slicing syntax follows that of the standard Python list; to access a slice of
an array x, use this:

x[start:stop:step]

_step_ can also be negative for reversing an array.

Multidimensional slices work in the same way, with multiple slices separated by commas.

In [4]:
x[:2,::-1]

array([[2, 7, 5, 3],
       [3, 0, 9, 8]])

Of course, this can be also used for accessing single rows or columns, by combining indexing and slicing

In [5]:
x[:,1]

array([ 5,  9, 25])

In [6]:
x[1,:]

array([8, 9, 0, 3])

One important feature of the Numpy Arrays is that unlike Python lists, slicing pieces of the array returns _views_ rather than _copies_ of the array data.

In [7]:
print(x)
x1 = x[:2,:3]
x1

[[ 3  5  7  2]
 [ 8  9  0  3]
 [ 8 25  2  2]]


array([[3, 5, 7],
       [8, 9, 0]])

In [8]:
x1[1,1]=12
print(x1)
print(x)

[[ 3  5  7]
 [ 8 12  0]]
[[ 3  5  7  2]
 [ 8 12  0  3]
 [ 8 25  2  2]]


For obtaining a copy of the data within an array or subarray we can use the _copy()_ method.

In [9]:
print(x)
x2 = x[:2,:3].copy()
x2

[[ 3  5  7  2]
 [ 8 12  0  3]
 [ 8 25  2  2]]


array([[ 3,  5,  7],
       [ 8, 12,  0]])

In [10]:
x2[1,1]=99
print(x2)
print(x)

[[ 3  5  7]
 [ 8 99  0]]
[[ 3  5  7  2]
 [ 8 12  0  3]
 [ 8 25  2  2]]
