# Reshaping, joining and splitting arrays

## Reshaping arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the _reshape()_ method. Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array, but with noncontiguous memory buffers this is not always the case. For example:

In [1]:
import numpy as np

grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. You can do this with the _reshape_ method, or more easily by making use of the _newaxis_ keyword within a slice operation:

In [2]:
x = np.array([1,2,3])

print(x.reshape((1,3)))
print(x)

[[1 2 3]]
[1 2 3]


In [3]:
print(x[np.newaxis, :])
print(x)

[[1 2 3]]
[1 2 3]


In [4]:
print(x.reshape((3,1)))
print(x)

[[1]
 [2]
 [3]]
[1 2 3]


In [5]:
print(x[:,np.newaxis])
print(x)

[[1]
 [2]
 [3]]
[1 2 3]


## Joining and splitting arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished through the routines _np.concatenate_, _np.vstack_, _np.hstack_ and _np.stack_.

_np.concatenate_ takes a tuple or list of arrays as its first argument, as we can see here:

In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
grid = np.array([[2,3,4],[5,6,7]])

print(np.concatenate([x,y,z]))
print(np.concatenate([grid,grid]))
print(np.concatenate([grid,grid],axis=1))

[1 2 3 4 5 6 7 8 9]
[[2 3 4]
 [5 6 7]
 [2 3 4]
 [5 6 7]]
[[2 3 4 2 3 4]
 [5 6 7 5 6 7]]


For working with arrays of mixed dimensions, it can be clearer to use the _np.vstack_ (vertical stack), _np.hstack_ (horizontal stack) and _np.dstack_ (third axis stacks) functions:

In [14]:
z = np.array([[1],[2]])
print(z)

print(np.vstack([x, grid]))
print(np.hstack([z, grid]))

[[1]
 [2]]
[[1 2 3]
 [2 3 4]
 [5 6 7]]
[[1 2 3 4]
 [2 5 6 7]]


## Splitting of arrays

Array splitting is implemented by the functions _np.split_, _np.hsplit_, and _np.vsplit_. For each of these, we can pass a list of indices giving the split points:

In [15]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


The related functions _np.hsplit_, _np.vsplit_ and _np.dsplit_ are similar:

In [16]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [18]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, np.dsplit will split arrays along the third axis.